- name: Demo on lineinfile
  hosts: nodes
  become: yes
  tasks:
    - name: Add a line to a file  
      lineinfile:
        path: /tmp/demo.txt
        line: '192.168.1.99 foo.lab.net foo'

    - name: Add a line with condition 
      lineinfile:
        path: /tmp/context.xml
        line: <Resource name="jdbc/TestDB" auth="Container" type="javax.sql.DataSource" maxActive="50" maxIdle="30" maxWait="10000" username="student" password="student@1" driverClassName="com.mysql.jdbc.Driver" url="jdbc:mysql://10.142.0.7:3306/studentapp"/>
        insertbefore: '</Context>'

    - name: Add a line with variables
      lineinfile:
        path: /tmp/context.xml
        line: <Resource name="jdbc/NewDB" auth="Container" type="javax.sql.DataSource" maxActive="50" maxIdle="30" maxWait="10000" username="student" password="student@1" driverClassName="com.mysql.jdbc.Driver" url="jdbc:mysql://{{IP}}:3306/studentapp"/>
        insertbefore: '</Context>'
      vars:
        IP: 192.168.1.1